  version: "3.9" #version of docker-compose
  services:
    mysql:
      container_name: mysql
      image: mysql
      ports:
      - "3307:3306"
      environment:
        - MYSQL_ROOT_PASSWORD=admin1     
      volumes:
        - ./data:/var/lib/mysql
        - ./src/main/db:/docker-entrypoint-initdb.d  
      restart: always                    #database data volume