CREATE DATABASE IF NOT EXISTS afishybusiness;
USE afishybusiness
GO
CREATE TABLE IF NOT EXISTS products(imageSrc VARCHAR(255) NOT NULL, productName VARCHAR(255) NOT NULL, productPrice FLOAT NOT NULL, id INT NOT NULL AUTO_INCREMENT PRIMARY KEY);
GO
CREATE TABLE IF NOT EXISTS users(email VARCHAR(255) NOT NULL PRIMARY KEY, password VARCHAR(255) NOT NULL, admin INT(1) NOT NULL);